name: List
on: pull_request

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        tfaction_version:
          - v1.5.2
          - v1.7.0
          - v1.10.0

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - uses: aquaproj/aqua-installer@4551ec64e21bf0f557c2525135ff0bd2cba40ec7 # v3.0.0
        with:
          aqua_version: v2.36.1
      - id: list-targets
        uses: suzuki-shunsuke/tfaction/list-targets@v1.10.0
      - run: echo "$NOTE" >> "$GITHUB_STEP_SUMMARY"
        env:
          NOTE: |

            ## ${{matrix.tfaction_version}}

            ```json
            ${{ steps.list-targets.outputs.targets }}
            ```
