name: List
on: pull_request

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        tfaction_version:
          - v1.5.2
          - v1.7.0
          - v1.10.0

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - uses: aquaproj/aqua-installer@6ce1f8848ec8e61f14d57bd5d7597057a6dd187c # v3.0.1
        with:
          aqua_version: v2.36.1
      - id: list-targets
        uses: suzuki-shunsuke/tfaction/list-targets@${{matrix.tfaction_version}}
      - run: echo "$NOTE" >> "$GITHUB_STEP_SUMMARY"
        env:
          NOTE: |

            ## ${{matrix.tfaction_version}}

            ```json
            ${{ steps.list-targets.outputs.targets }}
            ```
